### ISSUE TITLE
install.sh: line 84: syntax error near unexpected token `done'

### ISSUE THREAD

**Issue by Masriyan** [matamorphosis/Scrummage#55]
```
install.sh: line 84: syntax error near unexpected token `done'
install.sh: line 84: `    done'
```

**Comment by brian-larsen** [comment]
After checking the version history of install.sh, it looks like this is left over from a while loop that added lines to pyproject.toml from python_requirements.txt (no longer included). Removing or commenting out this line should eliminate that error.

**Comment by matamorphosis** [comment]
Hi @Masriyan @brian-larsen, thanks for your contributions. Due to the containerisation of this platform and a recent move to the Poetry package manager which created challenges for the existing manual installation option.

I would recommend moving to the docker image.

I have looked at the `install.sh` file, and can see that line was removed around 3 months ago, probably not long after this issue was raised. However, I'm not confident the `install.sh` script works, as it hasn't been tested for quite some time.
